# Generated by Django 3.0.6 on 2020-07-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
